### ISSUE TITLE
What is NAA?

### ISSUE THREAD

**Issue by Shunsuke-1994** [aleixalcacer/archetypes#22]
Hi, thank you for the nice package!

I am wondering what NAA is. I tried to find the reference, but I could not find it. 
I would appreciate if you could tell me the reference etc.

Best regards, 
Shunsuke

**Comment by aleixalcacer** [comment]
Hello, it is a method developed in a work in progress that I hope will be available in a few days. It is the extension of AA to N-dimensions. That is, with this method Archetype Analysis can be applied to n-dimensional tensors.

When I have it finished, I will create a Jupyter notebook explaining how it works.

Just out of curiosity, are you using this package in any projects? If yes, could you tell me what it is about? I like to see in which areas archetype analysis is used :)

**Comment by Shunsuke-1994** [comment]
Thank you for your response. 
I see. I look forward to seeing it!

I am using your package for analysis of ophthalmological data. In ophthalmology, archetypal analysis is relatively popular to extract potential disease patterns from observed data. e.g) https://royalsocietypublishing.org/doi/full/10.1098/rsif.2014.1118
