### ISSUE TITLE
BUG: Test failure due to ``scipy.optimize.nnls`` defect

### ISSUE THREAD

**Issue by wangzcl** [aleixalcacer/archetypes#23]
``v0.6.2`` fails to past the test, as ``scipy`` changed its ``optimize.nnls`` implementation since version ``1.12.0``, which results in error for certain Fortran-order arrays. I have submitted an [issue](https://github.com/scipy/scipy/issues/20813) to ``scipy``. Let's see how they handle it. Another option is to specify ``scipy`` version in ``pyproject.toml``: ``scipy==1.11.4`` or earlier.

**Comment by aleixalcacer** [comment]
I think it's best to wait, if they don't resolve it I agree to do what you say.

**Comment by aleixalcacer** [comment]
Finally, I changed the version to `scipy<1.12`. However, when it is fixed, I will switch back to the newer version.

Can the issue be closed?

**Comment by wangzcl** [comment]
Not sure if they have fixed the problem in scipy. I am OK with closing the issue. Hopefully we will not heavily rely on the approximate solution of NNLS after direct PGD is well implemented and tested (it can still be kept as an option though).

**Comment by aleixalcacer** [comment]
> Not sure if they have fixed the problem in scipy. I am OK with closing the issue. Hopefully we will not heavily rely on the approximate solution of NNLS after direct PGD is well implemented and tested (it can still be kept as an option though).

Any news on that? Are you working on it?

**Comment by wangzcl** [comment]
I just came back from a vacation, and yes, I have already done with orthogonal projection onto unit simplex with numpy in my fork. It may not be the fastest algorithm but it is easy to implement vectorize. The next step for me is to combine it with gradient descent. Seems that backtracking line search is our best option to adjust step size.

**Comment by aleixalcacer** [comment]
That sounds promising! Maybe could you keep a log of your progress in #27 ?

+1 to keep NNLS as option :)

**Comment by wangzcl** [comment]
scipy/scipy#21021 seems to have fixed the issue. It will be available in scipy 1.15.0.
