### ISSUE TITLE
Using the package on unseen data

### ISSUE THREAD

**Issue by Raoufsk** [aleixalcacer/archetypes#5]
Hello,
I am using this for my research, but I have very large datasets and it takes forever to fit. I was thinking I could train it on a small sample then apply the model directly to the rest of my datasets. But I don't know how to do that. Is that possible?

**Comment by aleixalcacer** [comment]
Are you using the `archetypes.AA` or the `archetypes.BiAA` estimator? I could add a new parameter called `verbose` that print progress :)

**Comment by Raoufsk** [comment]
Am using archetypes.AA estimator. Thank you!

**Comment by aleixalcacer** [comment]
If you install the new version of the package:

```
pip install archetypes==0.0.6
```

The flag `verbose` can be used to trace the progress:

```python
...
aa = arch.AA(n_archetypes=5, n_init=10, max_iter=1000, verbose=True, tol=1e-16, random_state=random_state)
aa.fit(X)
```
```
Initialization  1/10
    Iteration:    1, RSS: inf
    Iteration:  101, RSS: 0.81
    Iteration:  201, RSS: 0.81
Initialization  2/10
    Iteration:    1, RSS: inf
    Iteration:  101, RSS: 3.49
    Iteration:  201, RSS: 3.47
    Iteration:  301, RSS: 3.51
```

It is enough for you?

**Comment by Raoufsk** [comment]
Yes! Thank you so much :)
