### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by aleixalcacer** [aleixalcacer/archetypes#6]
- [ ] Use Sphinx + Read The Docs

**Comment by heidler** [comment]
I just tried your package, great! Documentation would be awesome! Maybe some tutorial on how to implement everything from start to end. I'm new to AA, so I'm looking forward to work with your package even more!

**Comment by aleixalcacer** [comment]
Hello, I'm glad you're using my package!

As you can see, I'm in progress in Pull Request #7. You can find the preliminary version of the docs at https://archetypes.readthedocs.io

I hope I can finish it soon! 🤞

On the other hand, could I know in what field you are using the archetypes? It is always good to know new fields of use :)

Aleix

**Comment by heidler** [comment]
Last week my friend introduced me to clustering, so I read something about k-means clustering and then went for archetype analysis primarly in sport fields. So right know, we are having fun with some data from sport performance testing.

Thanks to your package, we got our profiles very easily. :)

Thank you!

**Comment by aleixalcacer** [comment]
I hope it helped in you testings!

The documentation are already merged and published. If you find something wrong or have any improvements, feel free to open another issue :)
